name: Robot Framework Tests

on:
  # Runs on every push to main
  push:
    branches:
      - main
  # Scheduled run at 9 AM daily
  schedule:
    - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init  # needed for Browser library

      # Run tests
      - name: Run Robot Framework tests
        run: |
          robot -d results TestSuites/

      # Upload results as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
