name: Robot Framework Tests

on:
  # Manual trigger
  workflow_dispatch:

  # Scheduled run at 9 AM daily
  schedule:
    - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init

      # Run tests
      - name: Run Robot Framework tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "Running: SL automation scheduled run"
          else
            echo "Running: SL manual run"
          fi
          robot --variable BROWSER:headlesschromium -d results TestSuites/

      # Upload results as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/